const groups=[
 {name:'01 · FORMATO',items:{'/infographic':'Crea un’infografica con gerarchia visiva chiara, dati e callout essenziali.','/poster':'Imposta il risultato come un manifesto con un punto focale forte.','/blueprint':'Usa una tavola tecnica in stile blueprint con annotazioni funzionali.','/comic':'Racconta il contenuto attraverso vignette sequenziali.','/film-strip':'Mostra una sequenza temporale come fotogrammi consecutivi.','/cross-section':'Usa una vista in sezione per mostrare struttura e funzionamento.','/before-after':'Organizza un confronto visivo prima/dopo.'}},
 {name:'02 · STILE',items:{'/photorealistic':'Mantieni un aspetto fotografico credibile, con materiali, luce e proporzioni realistiche.','/minimal':'Riduci gli elementi al necessario e mantieni molto spazio visivo.','/editorial':'Usa un linguaggio editoriale professionale e una tipografia sobria.','/technical':'Privilegia precisione, leggibilità e linguaggio visivo tecnico.','/drawing':'Rendi il soggetto come illustrazione disegnata.','/no-ai-look':'Evita cliché, bagliori, plasticità e artifici tipici della grafica generativa.'}},
 {name:'03 · SCOPO',items:{'/linkedin':'Ottimizza composizione e leggibilità per un contenuto professionale LinkedIn.','/advertising':'Costruisci un visual pubblicitario con soggetto protagonista e messaggio immediato.','/how-it-works':'Spiega visivamente come funziona il soggetto o il processo.','/comparison':'Metti in evidenza differenze e somiglianze in modo immediato.','/timeline':'Rappresenta chiaramente un’evoluzione nel tempo.','/data':'Fai dei dati l’elemento principale della comunicazione.'}},
 {name:'04 · VINCOLI',items:{'/keep-original':'Se è presente un’immagine di partenza, mantieni geometria, prospettiva, proporzioni e oggetti non esplicitamente indicati per la modifica.','/preserve-product':'Non ridisegnare né reinterpretare il prodotto originale.','/preserve-logo':'Mantieni logo, marchio, spelling e proporzioni senza alterazioni.','/low-text':'Usa pochissimo testo, solo quello indispensabile.','/no-text':'Non inserire testo nell’immagine.','/strict':'Tratta i vincoli indicati come prioritari rispetto alle scelte estetiche.'}}
];
const selected=new Set(); const builder=document.querySelector('#builder');
groups.forEach(g=>{const s=document.createElement('section');s.className='group';s.innerHTML=`<h2>${g.name}</h2><div class="chips"></div>`;const c=s.querySelector('.chips');Object.keys(g.items).forEach(k=>{const b=document.createElement('button');b.className='chip';b.textContent=k;b.onclick=()=>{selected.has(k)?selected.delete(k):selected.add(k);b.classList.toggle('active');render()};c.appendChild(b)});builder.appendChild(s)});
const subject=document.querySelector('#subject'),slashLine=document.querySelector('#slashLine'),promptText=document.querySelector('#promptText');subject.addEventListener('input',render);
function render(){const tags=[...selected];slashLine.textContent=tags.length?tags.join(' '):'Scegli almeno una voce';const instructions=[];groups.forEach(g=>Object.entries(g.items).forEach(([k,v])=>{if(selected.has(k))instructions.push(v)}));const subj=subject.value.trim();promptText.textContent=(subj?`Obiettivo: ${subj}\n\n`:'')+(instructions.length?instructions.join(' '):'Seleziona le scorciatoie per costruire il prompt.')}
async function copy(text){try{await navigator.clipboard.writeText(text)}catch{}}
document.querySelector('#copySlash').onclick=()=>copy(slashLine.textContent);document.querySelector('#copyPrompt').onclick=()=>copy(promptText.textContent);document.querySelector('#reset').onclick=()=>{selected.clear();document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));subject.value='';render()};document.querySelector('#share').onclick=async()=>{const text=`${slashLine.textContent}\n\n${promptText.textContent}`;if(navigator.share)await navigator.share({title:'Visual Slash',text});else copy(text)};
let deferred;const install=document.querySelector('#install');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;install.hidden=false});install.onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;install.hidden=true}};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));render();
