const groups=[
 {name:'01 · FORMATO',help:'Che tipo di immagine vuoi ottenere?',items:{
 '/infographic':{title:'INFORMAZIONI IN UN’IMMAGINE',what:'Trasforma un argomento in una pagina facile da capire usando titoli, numeri, icone, frecce e piccoli testi.',use:'Spiegare un processo, riassumere dati, confrontare informazioni.',example:'Come funziona un temporale',prompt:'Crea un’infografica facile da capire, con titoli chiari, icone, numeri, frecce e brevi testi.'},
 '/poster':{title:'MANIFESTO',what:'Crea una singola immagine d’impatto con un messaggio principale che si capisce subito.',use:'Pubblicità, eventi, lanci di prodotto, social.',example:'Presenta un nuovo prodotto',prompt:'Imposta il risultato come un manifesto con un punto focale forte e un messaggio immediato.'},
 '/blueprint':{title:'DISEGNO TECNICO',what:'Mostra un oggetto come in una tavola di progettazione, con linee, indicazioni e dettagli tecnici.',use:'Macchine, prodotti, edifici e spiegazioni tecniche.',example:'Mostra le parti di un sollevatore',prompt:'Usa una tavola tecnica in stile blueprint con linee e annotazioni funzionali.'},
 '/comic':{title:'RACCONTO A VIGNETTE',what:'Racconta un’idea o una storia attraverso più scene illustrate in sequenza.',use:'Spiegazioni semplici, storytelling, formazione.',example:'Spiega un errore in 4 vignette',prompt:'Racconta il contenuto attraverso vignette sequenziali chiare.'},
 '/film-strip':{title:'SEQUENZA NEL TEMPO',what:'Mostra cosa succede in momenti successivi, come una serie di fotogrammi.',use:'Evoluzioni, procedure, prima-durante-dopo.',example:'Ora, +20 e +40 minuti',prompt:'Mostra una sequenza temporale come fotogrammi consecutivi.'},
 '/cross-section':{title:'GUARDA DENTRO',what:'Taglia idealmente un oggetto per mostrare cosa contiene e come sono disposte le parti interne.',use:'Motori, edifici, macchinari, anatomia.',example:'Mostra l’interno di un motore',prompt:'Usa una vista in sezione per mostrare struttura interna e funzionamento.'},
 '/before-after':{title:'PRIMA E DOPO',what:'Mostra affiancate la situazione iniziale e quella modificata.',use:'Restauri, ristrutturazioni, modifiche fotografiche, confronti.',example:'Officina prima e dopo la pulizia',prompt:'Organizza un confronto visivo prima/dopo immediato.'}}},
 {name:'02 · STILE',help:'Come vuoi che appaia?',items:{
 '/photorealistic':{title:'COME UNA FOTOGRAFIA',what:'Fa apparire l’immagine il più possibile reale, con luce, materiali e proporzioni credibili.',use:'Prodotti, ambienti, persone e scene reali.',example:'Prodotto fotografato in officina',prompt:'Mantieni un aspetto fotografico credibile, con materiali, luce e proporzioni realistiche.'},
 '/minimal':{title:'SOLO L’ESSENZIALE',what:'Toglie decorazioni e dettagli inutili per far emergere il messaggio principale.',use:'Presentazioni, pubblicità pulita, concetti semplici.',example:'Un prodotto, un titolo, niente altro',prompt:'Riduci gli elementi al necessario e mantieni molto spazio visivo.'},
 '/editorial':{title:'COME UNA RIVISTA',what:'Organizza immagini e testo con un aspetto pulito, autorevole e professionale.',use:'LinkedIn, report, articoli, presentazioni.',example:'Apertura di una rivista professionale',prompt:'Usa un linguaggio editoriale professionale e una tipografia sobria.'},
 '/technical':{title:'PRECISO E TECNICO',what:'Privilegia chiarezza, precisione e leggibilità rispetto agli effetti estetici.',use:'Macchinari, procedure, formazione tecnica.',example:'Spiega il funzionamento di una macchina',prompt:'Privilegia precisione, leggibilità e linguaggio visivo tecnico.'},
 '/drawing':{title:'DISEGNO / ILLUSTRAZIONE',what:'Rappresenta il soggetto come un disegno invece che come una fotografia.',use:'Concept, spiegazioni, immagini narrative.',example:'Una scena disegnata a matita',prompt:'Rendi il soggetto come illustrazione disegnata.'},
 '/no-ai-look':{title:'NON DEVE SEMBRARE “FATTO DALL’AI”',what:'Evita l’aspetto artificiale: luci eccessive, superfici plastiche, dettagli improbabili e decorazioni gratuite.',use:'Fotografie, prodotti, ambienti e comunicazione professionale.',example:'Una foto credibile e naturale',prompt:'Evita cliché, bagliori, plasticità e artifici tipici della grafica generativa.'}}},
 {name:'03 · SCOPO',help:'Dove o perché la userai?',items:{
 '/linkedin':{title:'PER LINKEDIN',what:'Adatta la composizione per essere chiara e professionale mentre si scorre il feed.',use:'Post professionali, annunci, approfondimenti.',example:'Immagine per accompagnare un post',prompt:'Ottimizza composizione e leggibilità per un contenuto professionale LinkedIn.'},
 '/advertising':{title:'PER PUBBLICIZZARE',what:'Mette il soggetto al centro e rende il messaggio immediato e memorabile.',use:'Prodotti, servizi, campagne, offerte.',example:'Lancio di un nuovo sollevatore',prompt:'Costruisci un visual pubblicitario con soggetto protagonista e messaggio immediato.'},
 '/how-it-works':{title:'SPIEGA COME FUNZIONA',what:'Fa capire visivamente passaggi, relazioni e funzionamento di qualcosa.',use:'Prodotti, processi, tecnologia, formazione.',example:'Come funziona il nowcasting',prompt:'Spiega visivamente come funziona il soggetto o il processo.'},
 '/comparison':{title:'CONFRONTA',what:'Mette due o più alternative una accanto all’altra per far vedere subito le differenze.',use:'Prodotti, metodi, caratteristiche, scenari.',example:'Soluzione A contro soluzione B',prompt:'Metti in evidenza differenze e somiglianze in modo immediato.'},
 '/timeline':{title:'MOSTRA L’EVOLUZIONE',what:'Ordina gli eventi dal prima al dopo per far capire quando accadono.',use:'Storia, progetti, previsioni, procedure.',example:'Evoluzione nelle prossime 2 ore',prompt:'Rappresenta chiaramente un’evoluzione nel tempo.'},
 '/data':{title:'FAI PARLARE I NUMERI',what:'Mette dati, percentuali e valori al centro dell’immagine.',use:'Risultati, statistiche, confronti numerici.',example:'Vendite per anno',prompt:'Fai dei dati l’elemento principale della comunicazione.'}}},
 {name:'04 · VINCOLI',help:'Cosa NON deve essere modificato?',items:{
 '/keep-original':{title:'NON CAMBIARE LA FOTO',what:'Mantiene prospettiva, oggetti, proporzioni e struttura della foto originale. Cambia solo ciò che chiedi.',use:'Ritocchi precisi su fotografie esistenti.',example:'Pulisci il pavimento, non cambiare altro',prompt:'Se è presente un’immagine di partenza, mantieni geometria, prospettiva, proporzioni e oggetti non esplicitamente indicati per la modifica.'},
 '/preserve-product':{title:'NON RIDISEGNARE IL PRODOTTO',what:'Mantiene forma, componenti e caratteristiche del prodotto originale.',use:'Cataloghi, pubblicità e ambientazioni di prodotti reali.',example:'Cambia l’officina, non il macchinario',prompt:'Non ridisegnare né reinterpretare il prodotto originale.'},
 '/preserve-logo':{title:'NON CAMBIARE IL LOGO',what:'Mantiene marchio, scritta, forma e proporzioni esattamente come nell’originale.',use:'Materiale aziendale e prodotti marchiati.',example:'Mantieni il logo Cormach originale',prompt:'Mantieni logo, marchio, spelling e proporzioni senza alterazioni.'},
 '/low-text':{title:'POCHE PAROLE',what:'Riduce il testo al minimo necessario per capire il messaggio.',use:'Social, poster, immagini che devono leggersi velocemente.',example:'Titolo + 3 indicazioni',prompt:'Usa pochissimo testo, solo quello indispensabile.'},
 '/no-text':{title:'NESSUNA SCRITTA',what:'Chiede un’immagine completamente visiva, senza titoli, etichette o parole.',use:'Foto, sfondi, visual da completare dopo.',example:'Solo il prodotto e l’ambiente',prompt:'Non inserire testo nell’immagine.'},
 '/strict':{title:'RISPETTA I VINCOLI ALLA LETTERA',what:'Dice di dare priorità alle tue istruzioni e di non inventare modifiche non richieste.',use:'Editing preciso e prodotti che non devono cambiare.',example:'Modifica esclusivamente ciò che indico',prompt:'Tratta i vincoli indicati come prioritari rispetto alle scelte estetiche.'}}}
];

const modes=[
 {id:'image',icon:'🖼️',title:'Un’immagine',slash:'/image',desc:'Foto, infografiche, poster, disegni e modifiche a immagini.',hint:'Scegli formato, stile, scopo e vincoli qui sotto.'},
 {id:'document',icon:'📄',title:'Un documento',slash:'/document',desc:'Report, offerte, manuali, lettere e documenti strutturati.',hint:'Esempio: /report /professional /concise /docx',tags:['/report','/proposal','/manual','/summary','/professional','/concise','/pdf','/docx']},
 {id:'data',icon:'📊',title:'Analizzare dati',slash:'/data-analysis',desc:'Confronti, tabelle, sintesi, grafici e fogli di calcolo.',hint:'Esempio: /analysis /comparison /table /xlsx',tags:['/analysis','/comparison','/table','/chart','/xlsx']},
 {id:'presentation',icon:'📽️',title:'Una presentazione',slash:'/presentation',desc:'Pitch, presentazioni commerciali, formative o riassuntive.',hint:'Esempio: /presentation /professional /concise /pptx',tags:['/presentation','/pitch','/professional','/concise','/pptx']},
 {id:'text',icon:'✍️',title:'Un testo',slash:'/text',desc:'Email, post, articoli, riassunti e riscritture.',hint:'Esempio: /email /professional /concise',tags:['/email','/linkedin-post','/article','/rewrite','/professional','/concise']},
 {id:'code',icon:'💻',title:'Del codice',slash:'/code',desc:'PWA, HTML, JavaScript, Python, debugging e documentazione.',hint:'Esempio: /pwa /javascript /debug /document-code',tags:['/pwa','/html','/javascript','/python','/debug','/document-code']}
];
let activeMode='image';
const recipes=[
 {icon:'📊',title:'Spiegare dati',desc:'Numeri e informazioni facili da capire.',tags:['/infographic','/editorial','/data','/low-text']},
 {icon:'⚙️',title:'Spiegare come funziona',desc:'Mostra passaggi e funzionamento.',tags:['/infographic','/technical','/how-it-works','/low-text']},
 {icon:'📱',title:'Creare un post social',desc:'Visual chiaro per LinkedIn.',tags:['/poster','/editorial','/linkedin','/low-text']},
 {icon:'📢',title:'Pubblicizzare un prodotto',desc:'Prodotto protagonista, messaggio immediato.',tags:['/poster','/photorealistic','/advertising','/preserve-product','/preserve-logo']},
 {icon:'📷',title:'Migliorare una fotografia',desc:'Più naturale e credibile.',tags:['/photorealistic','/no-ai-look']},
 {icon:'🔒',title:'Modificare senza cambiare il resto',desc:'Intervento preciso sulla foto originale.',tags:['/photorealistic','/keep-original','/strict']},
 {icon:'↔️',title:'Fare un confronto',desc:'Differenze visibili a colpo d’occhio.',tags:['/before-after','/editorial','/comparison','/low-text']},
 {icon:'🎞️',title:'Raccontare una storia',desc:'Una sequenza visiva semplice.',tags:['/film-strip','/editorial','/timeline','/low-text']}
];
const why={
 '/infographic':'per trasformare informazioni in una spiegazione visiva semplice.', '/poster':'per concentrare tutto in una singola immagine d’impatto.', '/blueprint':'per mostrare il soggetto come una tavola tecnica.', '/comic':'per raccontare l’idea attraverso vignette.', '/film-strip':'per mostrare una sequenza di momenti.', '/cross-section':'per far vedere cosa c’è dentro.', '/before-after':'per confrontare chiaramente prima e dopo.',
 '/photorealistic':'per ottenere un aspetto simile a una fotografia reale.', '/minimal':'per eliminare ciò che distrae.', '/editorial':'per dare un aspetto pulito e professionale.', '/technical':'per privilegiare precisione e chiarezza.', '/drawing':'per ottenere un’illustrazione anziché una foto.', '/no-ai-look':'per evitare un aspetto artificiale o troppo generato.',
 '/linkedin':'per adattare il visual a un post professionale.', '/advertising':'per mettere in primo piano il messaggio commerciale.', '/how-it-works':'per spiegare passaggi e funzionamento.', '/comparison':'per rendere evidenti le differenze.', '/timeline':'per ordinare gli eventi nel tempo.', '/data':'per mettere numeri e valori al centro.',
 '/keep-original':'per non cambiare prospettiva, oggetti e struttura della foto.', '/preserve-product':'per non ridisegnare il prodotto reale.', '/preserve-logo':'per mantenere il marchio invariato.', '/low-text':'per rendere il risultato leggibile velocemente.', '/no-text':'per ottenere un’immagine senza scritte.', '/strict':'per dare priorità assoluta ai vincoli indicati.'
};
const selected=new Set(); const builder=document.querySelector('#builder');

function tooltip(k,d){return `<div class="tip" role="tooltip"><strong>${d.title}</strong><p>${d.what}</p><small><b>Usalo per:</b> ${d.use}</small><small><b>Esempio:</b> “${d.example}”</small></div>`}
groups.forEach(g=>{const s=document.createElement('section');s.className='group';s.innerHTML=`<div class="group-title"><h2>${g.name}</h2><span>${g.help}</span></div><div class="chips"></div>`;const c=s.querySelector('.chips');Object.entries(g.items).forEach(([k,d])=>{const w=document.createElement('div');w.className='chip-wrap';const b=document.createElement('button');b.className='chip';b.textContent=k;b.setAttribute('aria-describedby','tip-'+k.slice(1));const t=document.createElement('div');t.innerHTML=tooltip(k,d);const tip=t.firstChild;tip.id='tip-'+k.slice(1);w.append(b,tip);b.onclick=()=>{selected.has(k)?selected.delete(k):selected.add(k);b.classList.toggle('active');render()};b.onfocus=()=>w.classList.add('show-tip');b.onblur=()=>w.classList.remove('show-tip');c.appendChild(w)});builder.appendChild(s)});
const subject=document.querySelector('#subject'),slashLine=document.querySelector('#slashLine'),promptText=document.querySelector('#promptText');subject.addEventListener('input',render);
function buildGeneralPrompt(mode,subj){const base={document:'Crea un documento ben strutturato e professionale. Organizza il contenuto con titoli chiari, sezioni logiche e un formato facile da leggere. Se opportuno, proponi il formato finale più adatto tra PDF o DOCX.',data:'Analizza i dati in modo rigoroso. Evidenzia risultati, differenze, anomalie e conclusioni; usa tabelle o grafici quando aiutano a capire. Se richiesto, prepara un foglio di calcolo XLSX.',presentation:'Crea una presentazione chiara e professionale. Definisci una sequenza logica di slide, un messaggio principale per slide, testo essenziale e indicazioni visuali. Se supportato, produci un file PPTX.',text:'Scrivi il testo richiesto con struttura, tono e lunghezza adatti allo scopo. Evita formule generiche e mantieni il linguaggio chiaro.',code:'Crea o modifica il codice richiesto. Privilegia semplicità, robustezza e manutenzione; spiega solo ciò che serve, indica i file coinvolti e verifica gli errori prevedibili.'}[mode.id];return `Obiettivo: ${subj}\n\n${base}\n\nPrima di finalizzare, verifica che il risultato rispetti l’obiettivo e non inventare dati mancanti.`}
function render(){const tags=[...selected];const mode=modes.find(m=>m.id===activeMode);if(activeMode!=='image'){slashLine.textContent=mode.slash;const subj=subject.value.trim();promptText.textContent=subj?buildGeneralPrompt(mode,subj):'Descrivi cosa vuoi ottenere: Visual Slash preparerà un prompt completo per questa categoria.';document.querySelector('#whyBox').innerHTML='<h3>Perché questa scelta?</h3><p><b>'+mode.title+'</b> — '+mode.desc+' Il prompt finale è in linguaggio naturale, così è più facile riutilizzarlo con AI diverse.</p>';return}slashLine.textContent=tags.length?tags.join(' '):'Scegli almeno una voce';const instructions=[];groups.forEach(g=>Object.entries(g.items).forEach(([k,d])=>{if(selected.has(k))instructions.push(d.prompt)}));const subj=subject.value.trim();promptText.textContent=(subj?`Obiettivo: ${subj}\n\n`:'')+(instructions.length?instructions.join(' '):'Seleziona le scorciatoie per costruire il prompt.'); const whyBox=document.querySelector('#whyBox'); if(whyBox){whyBox.innerHTML=tags.length?'<h3>Perché queste scelte?</h3>'+tags.map(t=>`<p><b>${t}</b> ${why[t]||''}</p>`).join(''):'<h3>Perché queste scelte?</h3><p>Quando scegli una voce, qui ti spiego in parole semplici perché può essere utile.</p>'}}
function applyTags(tags){selected.clear();document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));tags.forEach(t=>{selected.add(t);document.querySelectorAll('.chip').forEach(x=>{if(x.textContent===t)x.classList.add('active')})});render();document.querySelector('#builder').scrollIntoView({behavior:'smooth',block:'start'})}
const modeGrid=document.querySelector('#modeGrid'),modeInfo=document.querySelector('#modeInfo');
function renderModes(){modeGrid.innerHTML='';modes.forEach(m=>{const b=document.createElement('button');b.className='recipe'+(m.id===activeMode?' mode-active':'');b.innerHTML=`<span>${m.icon}</span><strong>${m.title}</strong><small>${m.desc}</small><span class="mode-slash">${m.slash}</span>`;b.onclick=()=>{activeMode=m.id;renderModes();renderModeInfo(m)};modeGrid.appendChild(b)});renderModeInfo(modes.find(m=>m.id===activeMode))}
function renderModeInfo(m){modeInfo.innerHTML=`<h3>${m.icon} ${m.title}</h3><p>${m.desc} <strong>${m.hint}</strong></p>${m.id!=='image'?`<p style="margin-top:10px"><b>Scorciatoie utili:</b> ${m.tags.join(' ')}</p>`:''}`; if(m.id!=='image'){subject.placeholder=placeholderFor(m.id)}}
function placeholderFor(id){return ({document:'Es. Prepara un report professionale sul mercato italiano...',data:'Es. Confronta questi dati e metti in evidenza differenze e anomalie...',presentation:'Es. Crea una presentazione commerciale di 8 slide...',text:'Es. Scrivi una email professionale e concisa...',code:'Es. Crea una PWA offline con service worker...'}[id]||'Descrivi cosa vuoi ottenere.')}
renderModes();
const recipeGrid=document.querySelector('#recipeGrid');recipes.forEach(r=>{const b=document.createElement('button');b.className='recipe';b.innerHTML=`<span>${r.icon}</span><strong>${r.title}</strong><small>${r.desc}</small>`;b.onclick=()=>applyTags(r.tags);recipeGrid.appendChild(b)});
function suggestFromText(text){const s=text.toLowerCase();let tags=[];const add=(...a)=>a.forEach(x=>{if(!tags.includes(x))tags.push(x)});if(/dato|numero|percent|statistic|grafico|vendit/.test(s))add('/infographic','/data','/low-text');if(/funzion|spiega|process|passagg|come fa/.test(s))add('/infographic','/technical','/how-it-works','/low-text');if(/linkedin|social|post/.test(s))add('/poster','/editorial','/linkedin','/low-text');if(/pubblic|vend|prodotto|offerta|cliente/.test(s))add('/poster','/photorealistic','/advertising','/preserve-product');if(/foto|fotografia|realistic|reale/.test(s))add('/photorealistic','/no-ai-look');if(/non camb|mantieni|solo|original|senza modific/.test(s))add('/keep-original','/strict');if(/confront|differenz|prima|dopo|versus| vs /.test(s))add('/before-after','/comparison','/low-text');if(/storia|sequenza|evoluz|tempo|momenti/.test(s))add('/film-strip','/timeline');if(/logo|marchio/.test(s))add('/preserve-logo');if(!tags.length)add('/infographic','/minimal','/low-text');return tags}
document.querySelector('#helpChoose').onclick=()=>{const t=subject.value.trim();if(!t){subject.focus();document.querySelector('#advisorMsg').textContent='Scrivi prima, con parole tue, cosa vuoi ottenere. Anche una frase semplice.';return}const tags=suggestFromText(t);applyTags(tags);document.querySelector('#advisorMsg').textContent='Ti ho proposto una combinazione di partenza. Puoi cambiare qualsiasi scelta.'};

async function copy(text){try{await navigator.clipboard.writeText(text)}catch{}}
document.querySelector('#copySlash').onclick=()=>copy(slashLine.textContent);document.querySelector('#copyPrompt').onclick=()=>copy(promptText.textContent);document.querySelector('#reset').onclick=()=>{selected.clear();document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));subject.value='';activeMode='image';renderModes();render()};document.querySelector('#share').onclick=async()=>{const text=`${slashLine.textContent}\n\n${promptText.textContent}`;if(navigator.share)await navigator.share({title:'Visual Slash',text});else copy(text)};
let deferred;const install=document.querySelector('#install');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;install.hidden=false});install.onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;install.hidden=true}};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));render();
