const C={
 image:{icon:'🖼️',title:'Un’immagine',desc:'Foto, infografiche, poster, disegni e modifiche a immagini.',groups:[
  ['01 · FORMATO','Che tipo di immagine vuoi ottenere?',[['/infographic','INFORMAZIONI IN UN’IMMAGINE','Trasforma informazioni in una pagina visiva facile da capire.','processi, dati, spiegazioni','Crea un’infografica chiara con titoli, icone, numeri, frecce e brevi testi.'],['/poster','MANIFESTO','Una singola immagine d’impatto con un messaggio principale.','pubblicità, eventi, lanci','Imposta il risultato come un manifesto con un punto focale forte.'],['/blueprint','DISEGNO TECNICO','Mostra un oggetto come in una tavola di progettazione.','macchine, prodotti, edifici','Usa una tavola tecnica in stile blueprint con linee e annotazioni.'],['/comic','RACCONTO A VIGNETTE','Racconta un’idea attraverso scene illustrate.','storytelling, formazione','Racconta il contenuto attraverso vignette sequenziali.'],['/film-strip','SEQUENZA NEL TEMPO','Mostra momenti successivi come fotogrammi.','evoluzioni, procedure','Mostra una sequenza temporale di fotogrammi consecutivi.'],['/cross-section','GUARDA DENTRO','Taglia idealmente un oggetto per mostrarne l’interno.','motori, edifici, macchinari','Usa una vista in sezione per mostrare struttura interna e funzionamento.'],['/before-after','PRIMA E DOPO','Mostra situazione iniziale e modificata affiancate.','restauri, confronti','Organizza un confronto visivo prima/dopo.']]],
  ['02 · STILE','Come vuoi che appaia?',[['/photorealistic','COME UNA FOTOGRAFIA','Aspetto realistico con luce, materiali e proporzioni credibili.','prodotti, ambienti, persone','Mantieni un aspetto fotografico credibile e naturale.'],['/minimal','SOLO L’ESSENZIALE','Elimina dettagli inutili per far emergere il messaggio.','visual puliti','Riduci gli elementi al necessario.'],['/editorial','COME UNA RIVISTA','Aspetto pulito, autorevole e professionale.','LinkedIn, articoli','Usa un linguaggio editoriale professionale e sobrio.'],['/technical','PRECISO E TECNICO','Privilegia chiarezza e precisione.','macchinari, procedure','Privilegia precisione, leggibilità e linguaggio tecnico.'],['/drawing','DISEGNO','Rappresenta il soggetto come illustrazione.','concept, storytelling','Rendi il soggetto come illustrazione disegnata.'],['/no-ai-look','NATURALE, NON ARTIFICIALE','Evita luci e superfici che fanno sembrare il risultato generato.','foto professionali','Evita cliché, bagliori e plasticità tipici della grafica generativa.']]],
  ['03 · SCOPO','Dove o perché la userai?',[['/linkedin','PER LINKEDIN','Adatta il visual a un feed professionale.','post professionali','Ottimizza composizione e leggibilità per LinkedIn.'],['/advertising','PER PUBBLICIZZARE','Mette soggetto e messaggio commerciale al centro.','prodotti, servizi','Costruisci un visual pubblicitario immediato.'],['/how-it-works','SPIEGA COME FUNZIONA','Mostra passaggi e relazioni.','prodotti, processi','Spiega visivamente come funziona il soggetto.'],['/comparison','CONFRONTA','Rende evidenti differenze e somiglianze.','prodotti, scenari','Metti in evidenza differenze e somiglianze.'],['/timeline','MOSTRA L’EVOLUZIONE','Ordina gli eventi nel tempo.','storia, previsioni','Rappresenta chiaramente un’evoluzione nel tempo.'],['/data','FAI PARLARE I NUMERI','Mette valori e percentuali al centro.','risultati, statistiche','Fai dei dati l’elemento principale.']]],
  ['04 · VINCOLI','Cosa NON deve essere modificato?',[['/keep-original','NON CAMBIARE LA FOTO','Mantiene prospettiva, oggetti e proporzioni; cambia solo ciò che chiedi.','ritocchi precisi','Mantieni geometria, prospettiva e oggetti non indicati per la modifica.'],['/preserve-product','NON RIDISEGNARE IL PRODOTTO','Mantiene forma e componenti del prodotto originale.','cataloghi, pubblicità','Non ridisegnare né reinterpretare il prodotto originale.'],['/preserve-logo','NON CAMBIARE IL LOGO','Mantiene marchio, scritta e proporzioni.','materiale aziendale','Mantieni logo, spelling e proporzioni senza alterazioni.'],['/low-text','POCHE PAROLE','Riduce il testo al minimo.','social, poster','Usa pochissimo testo, solo quello indispensabile.'],['/no-text','NESSUNA SCRITTA','Nessun titolo, etichetta o parola.','foto, sfondi','Non inserire testo nell’immagine.'],['/strict','RISPETTA ALLA LETTERA','Dà priorità ai vincoli e non inventa modifiche.','editing preciso','Tratta i vincoli come prioritari rispetto alle scelte estetiche.']]]]},
 document:{icon:'📄',title:'Un documento',desc:'Report, offerte, manuali, lettere e documenti strutturati.',groups:[
  ['01 · TIPO','Che documento vuoi creare?',[['/report','REPORT','Documento organizzato che analizza e presenta un argomento.','analisi, ricerche, risultati','Prepara un report strutturato con sezioni e conclusioni.'],['/proposal','PROPOSTA / OFFERTA','Documento per presentare una proposta a un cliente o decisore.','offerte commerciali, progetti','Prepara una proposta chiara con obiettivo, vantaggi e condizioni.'],['/manual','MANUALE / GUIDA','Spiega come usare o fare qualcosa passo per passo.','prodotti, procedure','Crea un manuale pratico ordinato per passaggi.'],['/letter','LETTERA','Testo formale o professionale indirizzato a qualcuno.','comunicazioni ufficiali','Scrivi una lettera completa e appropriata al destinatario.'],['/brochure','BROCHURE','Documento promozionale sintetico e visuale.','prodotti, servizi','Organizza il contenuto come brochure commerciale.'],['/summary','RIASSUNTO','Riduce un contenuto ai punti davvero importanti.','documenti lunghi','Crea un riassunto fedele e facile da leggere.']]],
  ['02 · STILE','Come deve essere scritto?',[['/professional','PROFESSIONALE','Tono chiaro, serio e adatto al lavoro.','clienti, direzione','Usa un tono professionale, preciso e naturale.'],['/simple','SEMPLICE','Parole comuni e frasi facili da capire.','pubblico non tecnico','Spiega tutto con linguaggio semplice.'],['/technical','TECNICO','Usa terminologia precisa quando serve.','manuali, specifiche','Usa linguaggio tecnico accurato senza ambiguità.'],['/concise','CONCISO','Va al punto ed evita ripetizioni.','documenti rapidi','Sii sintetico e rimuovi il superfluo.'],['/detailed','DETTAGLIATO','Approfondisce ogni parte utile.','report completi','Fornisci dettaglio sufficiente e sezioni complete.']]],
  ['03 · CONTENUTO','Cosa deve contenere?',[['/executive-summary','SINTESI INIZIALE','Apre con ciò che un decisore deve sapere subito.','direzione, management','Inizia con un executive summary breve e concreto.'],['/table','TABELLE','Organizza informazioni confrontabili in righe e colonne.','prezzi, caratteristiche','Usa tabelle quando rendono il contenuto più leggibile.'],['/comparison','CONFRONTO','Confronta alternative con criteri chiari.','prodotti, scenari','Inserisci un confronto strutturato tra le alternative.'],['/checklist','CHECKLIST','Trasforma attività o controlli in punti spuntabili.','procedure, verifiche','Inserisci una checklist operativa.'],['/sources','FONTI','Chiede di indicare da dove arrivano informazioni e dati.','ricerche, report','Cita chiaramente le fonti utilizzate e non inventarle.']]],
  ['04 · FORMATO FILE','In che formato vuoi riceverlo?',[['/docx','WORD · DOCX','Documento Word modificabile dopo la creazione.','report, offerte, manuali','Produci il risultato come file Word DOCX modificabile, se lo strumento lo supporta.'],['/pdf','PDF','Documento finito, facile da condividere e stampare.','versioni definitive','Produci il risultato come PDF ben impaginato, se supportato.'],['/md','MARKDOWN','Testo leggero e strutturato, utile anche su GitHub.','documentazione','Produci anche un file Markdown .md.'],['/txt','TESTO SEMPLICE','File senza impaginazione complessa.','note, compatibilità','Produci un file di testo .txt.']]]]},
 data:{icon:'📊',title:'Analizzare dati',desc:'Confronti, tabelle, sintesi, grafici e fogli di calcolo.',groups:[
  ['01 · COSA FARE','Che lavoro vuoi fare sui dati?',[['/analysis','ANALIZZA','Trova risultati, tendenze, anomalie e informazioni utili.','vendite, misure, dataset','Analizza i dati con metodo e riassumi le evidenze.'],['/comparison','CONFRONTA','Confronta periodi, prodotti o gruppi.','anno su anno, alternative','Confronta i gruppi con criteri coerenti.'],['/forecast','PREVISIONE','Stima sviluppi futuri solo quando i dati lo permettono.','trend, pianificazione','Se i dati sono sufficienti, crea una previsione dichiarando ipotesi e limiti.'],['/clean-data','PULISCI I DATI','Individua duplicati, errori e formati incoerenti.','file disordinati','Pulisci e normalizza i dati senza perdere informazioni.']]],
  ['02 · COME MOSTRARLI','Come vuoi capire i risultati?',[['/table','TABELLA','Mostra valori ordinati in righe e colonne.','confronti precisi','Presenta i risultati principali in tabelle chiare.'],['/chart','GRAFICI','Trasforma i numeri in grafici leggibili.','trend, confronti','Crea grafici appropriati ai dati e spiegane il significato.'],['/kpi','INDICATORI CHIAVE','Evidenzia pochi numeri davvero importanti.','dashboard, direzione','Identifica e mostra i KPI principali.'],['/summary','SINTESI','Spiega in poche righe cosa emerge.','decisioni rapide','Aggiungi una sintesi delle evidenze principali.']]],
  ['03 · RIGORE','Come deve trattare i dati?',[['/verify','VERIFICA','Controlla coerenza e possibili errori prima di concludere.','analisi affidabili','Verifica coerenza, valori mancanti e anomalie prima delle conclusioni.'],['/no-invent','NON INVENTARE','Non completa dati mancanti con supposizioni.','qualsiasi analisi','Non inventare valori mancanti; segnala ciò che non è disponibile.'],['/explain','SPIEGA','Spiega in parole semplici cosa significano i risultati.','pubblico non tecnico','Spiega le conclusioni con linguaggio semplice.']]],
  ['04 · FORMATO FILE','Come vuoi ricevere il lavoro?',[['/xlsx','EXCEL · XLSX','Foglio Excel modificabile con tabelle e, se utile, formule/grafici.','analisi operative','Produci un file Excel XLSX strutturato, se supportato.'],['/csv','CSV','Dati tabellari semplici e compatibili con molti programmi.','scambio dati','Produci anche un CSV pulito.'],['/pdf','PDF','Report finale con analisi e grafici.','condivisione','Produci un report PDF ben impaginato, se supportato.'],['/docx','WORD · DOCX','Report modificabile in Word.','relazioni','Produci un report Word DOCX, se supportato.']]]]},
 presentation:{icon:'📽️',title:'Una presentazione',desc:'Pitch, presentazioni commerciali, formative o riassuntive.',groups:[
  ['01 · TIPO','Che presentazione vuoi?',[['/presentation','PRESENTAZIONE','Sequenza di slide per spiegare un argomento.','riunioni, eventi','Crea una presentazione con sequenza logica di slide.'],['/pitch','PITCH','Presentazione breve per convincere o proporre un’idea.','progetti, startup, vendite','Crea un pitch breve, chiaro e persuasivo.'],['/commercial','COMMERCIALE','Presenta prodotto, vantaggi e proposta.','clienti, rete vendita','Crea una presentazione commerciale orientata al cliente.'],['/training','FORMAZIONE','Insegna un argomento passo per passo.','corsi, procedure','Crea slide didattiche progressive e comprensibili.']]],
  ['02 · STILE','Come deve apparire?',[['/professional','PROFESSIONALE','Pulita e adatta al lavoro.','aziende','Usa uno stile professionale e coerente.'],['/minimal','MINIMALE','Pochi elementi per slide.','presentazioni dal vivo','Mantieni ogni slide essenziale.'],['/visual','MOLTO VISIVA','Più immagini e schemi, meno testo.','storytelling','Privilegia visual, diagrammi e parole chiave.'],['/executive','PER DIREZIONE','Sintetica e centrata su decisioni e numeri.','management','Dai priorità a risultati, decisioni e prossimi passi.']]],
  ['03 · CONTENUTO','Cosa deve includere?',[['/charts','GRAFICI','Inserisce grafici dove aiutano a capire i dati.','risultati','Usa grafici appropriati e leggibili.'],['/speaker-notes','NOTE RELATORE','Aggiunge note che aiutano chi presenta.','presentazioni dal vivo','Aggiungi note del relatore separate dal testo delle slide.'],['/summary','SLIDE FINALE','Chiude con messaggi chiave.','qualsiasi presentazione','Concludi con una sintesi e i prossimi passi.']]],
  ['04 · FORMATO FILE','In che formato?', [['/pptx','POWERPOINT · PPTX','Presentazione PowerPoint modificabile.','riunioni, clienti','Produci un file PowerPoint PPTX, se supportato.'],['/pdf','PDF','Versione non modificabile, facile da condividere.','invio e stampa','Produci anche una versione PDF, se supportato.']]]]},
 text:{icon:'✍️',title:'Un testo',desc:'Email, post, articoli, riassunti e riscritture.',groups:[
  ['01 · TIPO','Che testo vuoi?',[['/email','EMAIL','Messaggio pronto da inviare.','lavoro, clienti','Scrivi un’email completa con oggetto se utile.'],['/linkedin-post','POST LINKEDIN','Post professionale leggibile nel feed.','LinkedIn','Scrivi un post LinkedIn naturale e professionale.'],['/article','ARTICOLO','Testo più lungo organizzato in sezioni.','blog, approfondimenti','Scrivi un articolo strutturato con titolo e sezioni.'],['/rewrite','RISCRIVI','Migliora un testo senza cambiarne il significato.','bozze','Riscrivi mantenendo significato e informazioni.'],['/summary','RIASSUMI','Riduce un testo ai punti essenziali.','documenti lunghi','Riassumi senza perdere i fatti importanti.']]],
  ['02 · TONO','Come deve suonare?',[['/professional','PROFESSIONALE','Serio ma naturale.','lavoro','Usa un tono professionale, non burocratico.'],['/simple','SEMPLICE','Facile da capire.','pubblico ampio','Usa parole comuni e frasi chiare.'],['/concise','BREVE','Va subito al punto.','messaggi rapidi','Sii conciso e rimuovi ripetizioni.'],['/persuasive','PERSUASIVO','Argomenta per convincere senza esagerare.','vendita, proposte','Rendi il testo persuasivo con argomenti concreti.']]],
  ['03 · CONTROLLO','Cosa deve rispettare?',[['/fact-check','CONTROLLA I FATTI','Distingue fatti, ipotesi e informazioni da verificare.','testi informativi','Verifica i fatti quando possibile e segnala incertezze.'],['/no-hype','NIENTE ESAGERAZIONI','Evita slogan e superlativi gratuiti.','comunicazione professionale','Evita iperboli e formule promozionali vuote.'],['/keep-meaning','NON CAMBIARE IL SENSO','Nelle riscritture conserva il messaggio originale.','editing','Mantieni significato, dati e intenzione originali.']]],
  ['04 · FORMATO','Come lo vuoi?', [['/plain-text','TESTO','Testo pronto da copiare.','messaggi','Fornisci il testo finale senza spiegazioni inutili.'],['/md','MARKDOWN','Testo strutturato con titoli ed elenchi.','web, GitHub','Fornisci il risultato in Markdown.']]]]},
 code:{icon:'💻',title:'Del codice',desc:'PWA, HTML, JavaScript, Python, debugging e documentazione.',groups:[
  ['01 · COSA CREARE','Che tipo di lavoro?', [['/pwa','PWA','Web app installabile e utilizzabile come app.','app web','Crea una PWA completa con manifest e service worker.'],['/website','SITO WEB','Pagine web responsive.','siti, landing page','Crea un sito web responsive e accessibile.'],['/script','SCRIPT','Programma piccolo per automatizzare un compito.','automazioni','Crea uno script semplice e robusto.'],['/debug','CORREGGI ERRORI','Trova e risolve problemi nel codice esistente.','bug','Analizza l’errore, individua la causa e proponi una correzione verificabile.']]],
  ['02 · TECNOLOGIA','Con quale tecnologia?', [['/html','HTML/CSS','Interfacce web senza framework.','web semplice','Usa HTML semantico e CSS responsive.'],['/javascript','JAVASCRIPT','Logica web nel browser o runtime JS.','web app','Usa JavaScript chiaro e compatibile.'],['/python','PYTHON','Script, dati e automazioni.','analisi, utility','Usa Python leggibile e dipendenze minime.']]],
  ['03 · QUALITÀ','Come deve essere il codice?', [['/simple','SEMPLICE','Evita complessità non necessaria.','tutti i progetti','Scegli la soluzione più semplice che soddisfa i requisiti.'],['/offline','OFFLINE','Funziona anche senza rete quando possibile.','PWA','Prevedi funzionamento offline e cache appropriata.'],['/privacy','PRIVACY','Minimizza raccolta e invio di dati.','app locali','Mantieni i dati locali quando possibile e documenta eventuali trasferimenti.'],['/document-code','DOCUMENTATO','Spiega struttura e uso senza commenti inutili.','manutenzione','Documenta installazione, struttura e punti importanti.']]],
  ['04 · CONSEGNA','Cosa deve consegnare?', [['/complete-files','FILE COMPLETI','Restituisce file completi, non frammenti scollegati.','progetti','Fornisci i file completi necessari e indica dove salvarli.'],['/zip','ZIP','Prepara un archivio del progetto se possibile.','consegna','Se supportato, crea uno ZIP pronto da usare.']]]]},
};
const recipes={image:[['📊','Spiegare dati',['/infographic','/data','/low-text']],['⚙️','Spiegare come funziona',['/infographic','/technical','/how-it-works']],['📢','Pubblicizzare un prodotto',['/poster','/photorealistic','/advertising']]],document:[['📑','Report per direzione',['/report','/professional','/executive-summary','/pdf']],['💼','Offerta modificabile',['/proposal','/professional','/table','/docx']],['📘','Manuale tecnico',['/manual','/technical','/checklist','/pdf']]],data:[['📈','Analisi in Excel',['/analysis','/table','/chart','/xlsx']],['↔️','Confronto dati',['/comparison','/verify','/summary','/xlsx']],['📄','Report dei dati',['/analysis','/chart','/summary','/pdf']]],presentation:[['💼','Presentazione commerciale',['/commercial','/professional','/visual','/pptx']],['🎯','Pitch breve',['/pitch','/minimal','/summary','/pptx']],['👔','Per la direzione',['/presentation','/executive','/charts','/pptx']]],text:[['✉️','Email professionale',['/email','/professional','/concise','/plain-text']],['in','Post LinkedIn',['/linkedin-post','/professional','/no-hype','/plain-text']],['📝','Riscrivi meglio',['/rewrite','/simple','/keep-meaning','/plain-text']]],code:[['📱','PWA offline',['/pwa','/javascript','/offline','/complete-files']],['🐛','Correggi un bug',['/debug','/simple','/document-code','/complete-files']],['🔒','App locale e privata',['/pwa','/privacy','/offline','/zip']]]};

let active='image', selected=new Set(), locale='en', I18N=null;
const SUPPORTED=['it','en','de','es','fr','pt','zh-CN'];
const $=s=>document.querySelector(s), builder=$('#builder'), subject=$('#subject');
function normalizeLang(x=''){x=x.toLowerCase(); if(x.startsWith('zh'))return 'zh-CN'; if(x.startsWith('it'))return 'it'; if(x.startsWith('de'))return 'de'; if(x.startsWith('es'))return 'es'; if(x.startsWith('fr'))return 'fr'; if(x.startsWith('pt'))return 'pt'; return 'en'}
function detectedLang(){return normalizeLang(navigator.languages?.[0]||navigator.language||'en')}
async function loadLocale(lang){lang=SUPPORTED.includes(lang)?lang:'en'; try{const r=await fetch(`./i18n/${lang}.json?v=0.7.0`,{cache:'no-store'}); if(!r.ok)throw 0; I18N=await r.json(); locale=lang}catch(e){if(lang!=='en')return loadLocale('en'); throw e} document.documentElement.lang=locale==='zh-CN'?'zh-CN':locale; applyStaticText(); renderModes(); renderBuilder(); renderOutput(); updateLangButton()}
function t(k){return I18N?.ui?.[k]||k}
function modeText(id){return I18N?.modes?.[id]||[C[id].title,C[id].desc]}
function localizedGroup(g,idx){if(locale==='it'||!I18N?.groups)return [g[0],g[1]]; const set=I18N.groups[active]; return set?.[idx]||[g[0],g[1]]}
function slashLabel(key,d){if(locale==='it')return d?.[1]||key; return I18N?.slashLabels?.[key]||key.replace(/^\//,'').replace(/-/g,' ')}
function simpleTip(d){if(locale==='it')return `<div class="tip"><strong>${d[1]}</strong><p>${d[2]}</p><small><b>${t('useFor')}:</b> ${d[3]}</small></div>`; const label=slashLabel(d[0],d); const explain={en:`This tells the AI to use: ${label}.`,de:`Damit sagst du der KI: ${label}.`,es:`Esto indica a la IA que use: ${label}.`,fr:`Cela indique à l’IA d’utiliser : ${label}.`,pt:`Isto indica à IA para usar: ${label}.`,'zh-CN':`这会告诉 AI 使用：${label}。`}[locale]||label; return `<div class="tip"><strong>${label}</strong><p>${explain}</p><small><b>${t('useFor')}:</b> ${label}</small></div>`}
function allItems(){return C[active].groups.flatMap(g=>g[2])}
function item(k){return allItems().find(x=>x[0]===k)}
function renderBuilder(){builder.innerHTML=''; C[active].groups.forEach((g,idx)=>{const lg=localizedGroup(g,idx);let s=document.createElement('section');s.className='group';s.innerHTML=`<div class="group-title"><h2>${lg[0]}</h2><span>${lg[1]}</span></div><div class="chips"></div>`;let ch=s.querySelector('.chips');g[2].forEach(d=>{let w=document.createElement('div');w.className='chip-wrap';w.innerHTML=`<button class="chip ${selected.has(d[0])?'active':''}" aria-describedby="tip-${d[0].slice(1)}">${d[0]}</button>${simpleTip(d)}`;let b=w.querySelector('button');b.onclick=()=>{selected.has(d[0])?selected.delete(d[0]):selected.add(d[0]);renderBuilder();renderOutput()};b.onfocus=()=>w.classList.add('show-tip');b.onblur=()=>w.classList.remove('show-tip');ch.append(w)});builder.append(s)});}
function renderModes(){let grid=$('#modeGrid');grid.innerHTML='';Object.entries(C).forEach(([id,m])=>{const [title,desc]=modeText(id);let b=document.createElement('button');b.className='recipe '+(id===active?'mode-active':'');b.innerHTML=`<span>${m.icon}</span><strong>${title}</strong><small>${desc}</small>`;b.onclick=()=>switchMode(id);grid.append(b)});let m=C[active],[title,desc]=modeText(active);$('#modeInfo').innerHTML=`<h3>${m.icon} ${title}</h3><p>${desc} <strong>${t('categoryChange')}</strong></p>`;renderRecipes()}
function renderRecipes(){let g=$('#recipeGrid');g.innerHTML='';recipes[active].forEach(r=>{let b=document.createElement('button');b.className='recipe';const first=item(r[2][0]);b.innerHTML=`<span>${r[0]}</span><strong>${slashLabel(r[2][0],first)}</strong><small>${t('recipeHint')}</small>`;b.onclick=()=>apply(r[2]);g.append(b)})}
const placeholders={it:{image:'Es. Mostra una cella temporalesca e la posizione prevista tra 40 minuti.',document:'Es. Prepara un report sul mercato italiano, modificabile in Word.',data:'Es. Confronta vendite 2025 e 2026 e crea un Excel con grafici.',presentation:'Es. Prepara 8 slide per presentare il progetto alla direzione.',text:'Es. Scrivi una email professionale al cliente per...',code:'Es. Crea una PWA offline con service worker che...'},en:{image:'E.g. Show a storm cell now and its expected position in 40 minutes.',document:'E.g. Prepare a market report editable in Word.',data:'E.g. Compare 2025 and 2026 sales and create an Excel file with charts.',presentation:'E.g. Prepare 8 slides for management.',text:'E.g. Write a professional email to the client about...',code:'E.g. Create an offline PWA with a service worker that...'},de:{image:'Z. B. Zeige eine Gewitterzelle jetzt und ihre erwartete Position in 40 Minuten.',document:'Z. B. Erstelle einen Marktbericht, der in Word bearbeitbar ist.',data:'Z. B. Vergleiche Verkäufe 2025 und 2026 und erstelle Excel mit Diagrammen.',presentation:'Z. B. Erstelle 8 Folien für die Geschäftsleitung.',text:'Z. B. Schreibe eine professionelle E-Mail an den Kunden über...',code:'Z. B. Erstelle eine Offline-PWA mit Service Worker, die...'},es:{image:'Ej. Muestra una célula de tormenta ahora y su posición prevista en 40 minutos.',document:'Ej. Prepara un informe de mercado editable en Word.',data:'Ej. Compara ventas 2025 y 2026 y crea un Excel con gráficos.',presentation:'Ej. Prepara 8 diapositivas para dirección.',text:'Ej. Escribe un correo profesional al cliente sobre...',code:'Ej. Crea una PWA offline con service worker que...'},fr:{image:'Ex. Montrez une cellule orageuse maintenant et sa position prévue dans 40 minutes.',document:'Ex. Préparez un rapport de marché modifiable dans Word.',data:'Ex. Comparez les ventes 2025 et 2026 et créez un Excel avec graphiques.',presentation:'Ex. Préparez 8 diapositives pour la direction.',text:'Ex. Rédigez un e-mail professionnel au client au sujet de...',code:'Ex. Créez une PWA hors ligne avec service worker qui...'},pt:{image:'Ex. Mostre uma célula de tempestade agora e a posição prevista em 40 minutos.',document:'Ex. Prepare um relatório de mercado editável em Word.',data:'Ex. Compare vendas de 2025 e 2026 e crie um Excel com gráficos.',presentation:'Ex. Prepare 8 slides para a direção.',text:'Ex. Escreva um e-mail profissional ao cliente sobre...',code:'Ex. Crie uma PWA offline com service worker que...'},'zh-CN':{image:'例如：显示当前雷暴单体以及 40 分钟后的预计位置。',document:'例如：制作一份可在 Word 中编辑的市场报告。',data:'例如：比较 2025 和 2026 年销售数据，并制作带图表的 Excel。',presentation:'例如：为管理层准备 8 页幻灯片。',text:'例如：给客户写一封关于……的专业邮件。',code:'例如：创建一个带 Service Worker、可离线使用的 PWA。'}};
function switchMode(id){active=id;selected.clear();subject.placeholder=(placeholders[locale]||placeholders.en)[id];renderModes();renderBuilder();renderOutput();requestAnimationFrame(()=>$('#modeInfo').scrollIntoView({behavior:'smooth',block:'start'}))}
function apply(tags){selected=new Set(tags);renderBuilder();renderOutput();builder.scrollIntoView({behavior:'smooth',block:'start'})}
function renderOutput(){let tags=[...selected], subj=subject.value.trim();$('#slashLine').textContent=tags.length?tags.join(' '):t('selectedNone');let labels=tags.map(k=>slashLabel(k,item(k)));let objective=subj||`[${t('subject').toLowerCase()}]`;let prompt=`${t('objective')}: ${objective}.\n\n${t('resultType')}: ${modeText(active)[0]}. `;if(labels.length)prompt+=`${t('requirements')}: ${labels.join('; ')}. `;else prompt+=t('chooseOptions')+' ';prompt+=t('finalCheck');$('#promptText').textContent=prompt;$('#whyBox').innerHTML=`<h3>${t('why')}</h3>`+(tags.length?tags.map(k=>`<p><b>${k}</b> ${slashLabel(k,item(k))}</p>`).join(''):`<p>${modeText(active)[0]}. ${t('whyIntro')}</p>`)}
subject.addEventListener('input',renderOutput);
function infer(t0){let t=t0.toLowerCase();let mode=active,tags=[];if(/excel|xlsx|csv|dati|datos|daten|données|dados|数据|vendite|ventas|verkäufe|ventes|vendas|grafico|gráfico|diagramm|chart|图表/.test(t)){mode='data';tags=['/analysis','/table','/chart',/pdf/.test(t)?'/pdf':'/xlsx']}else if(/powerpoint|pptx|slide|diapos|folien|presentaci|présent|apresenta|演示|幻灯/.test(t)){mode='presentation';tags=['/presentation','/professional','/pptx']}else if(/word|docx|pdf|report|bericht|informe|rapport|relatório|报告|document|dokument|documento|文档|manual|handbuch|manuel|手册|offerta|angebot|oferta|proposta|proposal/.test(t)){mode='document';tags=[/manual|handbuch|manuel|手册/.test(t)?'/manual':/offerta|angebot|oferta|proposta|proposal/.test(t)?'/proposal':'/report','/professional',/word|docx/.test(t)?'/docx':'/pdf']}else if(/email|e-mail|correo|courriel|post|beitrag|publication|publicação|帖子|artikel|artículo|article|artigo|文章|riscr|rewrite|reescri|réécri|umschreib|改写|text|texto|texte|文本/.test(t)){mode='text';tags=[/email|e-mail|correo|courriel/.test(t)?'/email':/linkedin|post|beitrag|publication|publicação|帖子/.test(t)?'/linkedin-post':/riscr|rewrite|reescri|réécri|umschreib|改写/.test(t)?'/rewrite':'/article','/professional','/plain-text']}else if(/codice|code|código|代码|pwa|html|javascript|python|bug|debug|fehler|erreur|erro/.test(t)){mode='code';tags=[/bug|debug|fehler|erreur|erro/.test(t)?'/debug':'/pwa',/python/.test(t)?'/python':'/javascript','/simple','/complete-files']}else{mode='image';tags=['/infographic','/minimal','/low-text']}return [mode,tags]}
$('#helpChoose').onclick=()=>{let txt=subject.value.trim();if(!txt){subject.focus();$('#advisorMsg').textContent=t('writeFirst');return}let [m,tags]=infer(txt);active=m;selected=new Set(tags);renderModes();renderBuilder();renderOutput();$('#advisorMsg').textContent=`${t('recommend')}: ${modeText(m)[0]}. ${t('prepared')}`;builder.scrollIntoView({behavior:'smooth'})};
async function copy(txt){try{await navigator.clipboard.writeText(txt)}catch{}}
$('#copySlash').onclick=()=>copy($('#slashLine').textContent);$('#copyPrompt').onclick=()=>copy($('#promptText').textContent);$('#reset').onclick=()=>{active='image';selected.clear();subject.value='';renderModes();renderBuilder();renderOutput()};$('#share').onclick=async()=>{let text=$('#slashLine').textContent+'\n\n'+$('#promptText').textContent;if(navigator.share)await navigator.share({title:'Visual Slash',text});else copy(text)};
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#install').hidden=false});$('#install').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;$('#install').hidden=true}};
function applyStaticText(){const u=I18N.ui;$('#tagline').textContent=u.tagline;$('#hero1').textContent=u.hero1;$('#hero2').textContent=u.hero2;$('#heroP').textContent=u.heroP;$('#before').textContent=u.before;$('#guideTitle').textContent=u.guideTitle;$('#guideLead').textContent=u.guideLead;document.querySelectorAll('.ai-step').forEach((el,i)=>{let [a,b]=u.steps[i].split('|');el.innerHTML=`<b>${i+1} · ${a}</b>${b}`});$('#note').textContent=u.note;$('#startLabel').textContent=u.start;$('#whatTitle').textContent=u.what;$('#whatSub').textContent=u.whatSub;$('#dontKnow').textContent=u.dontKnow;$('#advisorText').textContent=u.advisor;$('#helpChoose').textContent=u.suggest;$('#subjectLabel').textContent=u.subject;$('#whyBox').innerHTML=`<h3>${u.why}</h3><p>${u.whyIntro}</p>`;$('#slashTitle').textContent=u.slashOut;$('#promptTitle').textContent=u.promptOut;$('#copySlash').textContent=u.copySlash;$('#copyPrompt').textContent=u.copyPrompt;$('#share').textContent=u.share;$('#reset').textContent=u.reset;$('#install').textContent=u.install;$('#aboutTitle').textContent=u.aboutTitle;$('#aboutText').textContent=u.about;$('#footer').textContent=`Visual Slash v0.7.0 · Alessandro Pezzali · Open source`;subject.placeholder=(placeholders[locale]||placeholders.en)[active]}
function updateLangButton(){$('#langBtn').textContent='🌐 '+({it:'IT',en:'EN',de:'DE',es:'ES',fr:'FR',pt:'PT','zh-CN':'中文'}[locale]||locale)}
function openLanguagePicker(first=false){const modal=$('#languageModal');modal.hidden=false;modal.classList.toggle('first-open',first);const detected=detectedLang();$('#langDetected').textContent=`${(I18N?.ui?.detected)||'Device language detected'}: ${detected}`;document.querySelectorAll('.lang-choice').forEach(b=>b.classList.toggle('active',b.dataset.lang===(first?detected:locale)))}
function closeLanguagePicker(){if(!localStorage.getItem('vs-language'))return;$('#languageModal').hidden=true}
document.querySelectorAll('.lang-choice').forEach(b=>b.onclick=async()=>{const lang=b.dataset.lang;localStorage.setItem('vs-language',lang);await loadLocale(lang);$('#languageModal').hidden=true});$('#langBtn').onclick=()=>openLanguagePicker(false);$('#languageClose').onclick=closeLanguagePicker;
const APP_VERSION='0.7.0';
if('serviceWorker' in navigator){window.addEventListener('load',async()=>{try{const reg=await navigator.serviceWorker.register('./sw.js?v='+APP_VERSION,{updateViaCache:'none'});await reg.update();let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(refreshing)return;refreshing=true;location.reload()});setInterval(()=>reg.update().catch(()=>{}),60*1000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')reg.update().catch(()=>{})})}catch(e){console.warn('Service Worker unavailable',e)}})}
(async()=>{const stored=localStorage.getItem('vs-language');const initial=stored&&SUPPORTED.includes(stored)?stored:detectedLang();await loadLocale(initial); if(!stored)openLanguagePicker(true)})();
